[package]
name = "jetson_gpio"
version = "0.1.0"
authors = ["Josh <augeas275@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
